Fix l10n.proj
sillsdev/libpalaso pull request #1151
Opened 2022-03-28 16:12 UTC by ermshiperete

- use GitVersion.MsBuild instead of deprecated GitVersionTask
- use TargetFramework**s** (plural) because that's defined in the parent Directory.Build.props
- 

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1151)

2022-03-28 16:13 UTC, tombogle approved these changes

2022-03-28 16:18 UTC, tombogle requested changes
Still doesn't solve the problem

2022-03-29 14:35 UTC, ermshiperete commented
The problem was that `<TargetFrameworks>` is already defined in `Directory.Build.props` and confused things.

2022-03-29 19:09 UTC, tombogle approved these changes

2022-03-29 19:09 UTC, merged