Add several RobustFile and RobustIO methods and enhance RetryUtility
sillsdev/libpalaso pull request #1283
Opened 2023-09-12 16:54 UTC by StephenMcConnel

Almost all of the methods have been implemented and used in Bloom for some time.  (and flagged for moving to libpalaso)
The enhancements to RetryUtility have been useful for finding problems and verifying the operation of the Robust methods.

2023-09-12 23:17 UTC, andrew-polk requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1283)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[`SIL.Core/IO/RobustFile.cs` line 406 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1283#-NeAflIj8sibkhkrDef9:-NeAflIj8sibkhkrDefA:b-7fugqs) ([raw file](https://github.com/sillsdev/libpalaso/blob/77c97894cbd7015e096fd51f0595dd1c45e7a97e/SIL.Core/IO/RobustFile.cs#L406)):*
> ```Smalltalk
> 				return sb.ToString();
> 			}
> 		}
> ```

Maybe these two methods would be better in RobustIO since it isn't a replacement for a System.IO.File method?


<!-- Sent from Reviewable.io -->

2023-09-13 07:48 UTC, ermshiperete requested changes

2023-09-13 07:48 UTC, ermshiperete commented on SIL.Core.Desktop/IO/RobustImageIO.cs
> +		/// so we use FromStream instead.  For details, see the last answer to
This comment seems to be a bit outdated. I don't see `FromStream` anywhere.

2023-09-13 16:53 UTC, ermshiperete approved these changes
LGTM

2023-09-13 17:37 UTC, andrew-polk approved these changes
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1283)* status: all files reviewed, 3 unresolved discussions (waiting on @ermshiperete)



<!-- Sent from Reviewable.io -->

2023-09-13 18:21 UTC, StephenMcConnel commented
@ermshiperete - 3 "conversations" are still "unresolved" even though they are also "outdated".  How do we get past this state?

2023-09-13 20:26 UTC, StephenMcConnel commented
I found out that I could resolve the conversations, and perhaps needed to?

2023-09-13 20:28 UTC, StephenMcConnel reviewed
Except that now they're still pending even though resolved.  I don't understand this protocol for reviewing apparently...

> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1283#-:-NeFDXSF-wAb4njwJ7iF:bwtixnl)* status: all files reviewed, 3 unresolved discussions (waiting on @ermshiperete)



<!-- Sent from Reviewable.io -->

2023-09-13 20:29 UTC, merged

2023-09-14 07:41 UTC, ermshiperete commented
@StephenMcConnel I didn't use Reviewable to do my review, that's why Reviewable still shows them as being unresolved. You can just ignore them and merge anyways (as you did).