Add a macOS-compatible global lock
sillsdev/libpalaso pull request #1327
Opened 2024-06-06 17:35 UTC by lyonsil

2024-06-06 18:11 UTC, tombogle commented on SIL.Core/Threading/GlobalMutex.cs
>  		public GlobalMutex(string name)
Do we need to document that (on Mac) the actual mutex might not be named as requested? (Probably not important since it will always work like this.)

2024-06-06 18:55 UTC, lyonsil reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1327)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @tombogle)

___
*[`SIL.Core/Threading/GlobalMutex.cs` line 28 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1327#gh-1630006175:-Nziq1RGEiAJR_I9SiJN:b-4tk9gd) ([raw file](https://github.com/sillsdev/libpalaso/blob/0aed06d6c7a7c9bc8663cf2b97b6de543abf070e/SIL.Core/Threading/GlobalMutex.cs#L28)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

Do we need to document that (on Mac) the actual mutex might not be named as requested? (Probably not important since it will always work like this.)
</blockquote></details>

I added more comments to explain things in more detail.


<!-- Sent from Reviewable.io -->

2024-06-06 19:23 UTC, tombogle approved these changes

2024-06-06 19:25 UTC, tombogle requested changes
There should be an entry in the changelog.md. In once sense, perhaps, this should be marked as semver:minor. On Mac, it is a new bit of functionality even though technically the interface itself didn't change.

2024-06-06 19:58 UTC, lyonsil reviewed
Done

> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1327#-:-Nzj7PsB88Hzt2St0gwx:bb6un1j)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @tombogle)



<!-- Sent from Reviewable.io -->

2024-06-10 15:34 UTC, tombogle approved these changes

2024-06-10 15:34 UTC, tombogle approved these changes
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1327)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lyonsil)



<!-- Sent from Reviewable.io -->

2024-06-10 17:23 UTC, merged