Use the SIL fork of NAudio for large file support
sillsdev/libpalaso pull request #943
Opened 2020-05-20 15:58 UTC by phillip-hopper

2020-05-20 17:55 UTC, ermshiperete requested changes
Would be nice to have a released version of SIL.NAudio before we release libpalaso 9.0

2020-05-20 17:55 UTC, ermshiperete commented on SIL.Media/SIL.Media-Designer.csproj
> +    <ProjectReference Include="SIL.Media.csproj">
Do we need this project reference?

2020-05-20 17:55 UTC, ermshiperete commented on SIL.Media/SIL.Media.csproj
> +      <PrivateAssets>all</PrivateAssets>
Do we really want `<PrivateAssets>all</PrivateAssets>` for `SIL.NAudio`? I'd think that we need the assembly at runtime, not just during the build.

2020-05-21 16:37 UTC, tombogle commented
After talking with Zac Glenn, he thinks that before we defnitely commit to this, it would be good to take one more crack at seeing if we can get the official NAudio master to build and try to get our failing Nunit tasks into a branch so we can demonstrate that the bug still exists (or find out that it doesn't). if it does, we can create an issue in their guthub, and then he would be willing to negotiate with them if necessary to get it fixed (we could easily do the work I think).

2020-06-17 11:52 UTC, closed without merging

2026-06-16 10:42 UTC, imnasnainaec commented
Can this branch be deleted?

2026-06-16 13:15 UTC, tombogle commented
Most likely. I *thought* there was still something that relied on our fork of NAudio, but I've searched and found nothing. On Nuget, we have only one package that is not marked as "pre-release" but even that one has "beta" in it's name, so that's highly suspect. And the project is archived on TeamCity.
It's a rather fuzzy memory, but I think the version(s) of 1.x that we use did incorporate our fixes for large audio files, but then maybe that got broken again in v. 2.
I do have a task on my to-do list to see if we could upgrade to NAudio v. 3, [which claims to restore full support for large audio files](https://github.com/naudio/NAudio/pull/437#event-25835182944). This seems to be a pretty major breaking change but could be really beneficial.